# Название вашего приложения
spring.application.name=social-navigator

# Сетевые настройки сервера
server.address=0.0.0.0
server.port=8086



# Настройки подключения к базе данных PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/social_navigator
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки JPA (Java Persistence API) и Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Настройки Thymeleaf (шаблонизатор)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Настройки логирования
# Уровни логирования должны быть одними из: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging.level.org.springframework=INFO
logging.level.org.springframework.security=DEBUG
logging.level.com.social_navigator_ar.demo=DEBUG
# Исправлено: комментарий убран с той же строки, что и значение
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Настройки Spring MVC
spring.mvc.hiddenmethod.filter.enabled=true

# Настройки отображения сообщений об ошибках сервера
server.error.include-message=always

# ???? ? ????? ????????
upload.path=src/main/resources/static/uploads

# ??????????? ??????? ??????????? ??????
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB